### ISSUE TITLE
Can't hide "expansion name" factions

### ISSUE THREAD

**Issue by SirJorb** [teelolws/InactiveReputationHeaders#5] opened 2022-12-25 00:39 UTC
Got some bug(?) factions about a month ago named "Cataclysm" and "The Burning Crusade" that I can't get rid of, with this addon or otherwise. Would be nice if they could be set to inactive or even outright hidden (since they seem to be junk factions).

![image](https://user-images.githubusercontent.com/23423782/209454057-156d35bc-e012-4d55-9db9-d423aa353033.png)
![image](https://user-images.githubusercontent.com/23423782/209454061-f969aa4f-b44d-4ad2-9e57-49c143997622.png)
![image](https://user-images.githubusercontent.com/23423782/209454063-e8816898-c40d-43ad-b013-911420a714cb.png)

**Comment by teelolws** [comment] 2022-12-25 00:45
Yeah I'm not sure whats going on with those headers. I'm waiting for a chance to get on the 10.0.5 PTR to see if they're fixing it.

**Comment by teelolws** [comment] 2023-01-21 06:12
Bug seems to be fixed on the 10.0.5PTR. Will add Valdrakken Accord support with the 10.0.5 patch.

**Comment by Hinkyz** [comment] 2023-04-13 15:24
This issue is still happening, as well as the valdrakken accord one.

**Comment by teelolws** [comment] 2023-04-13 21:11
> This issue is still happening, as well as the valdrakken accord one.

Can you show me a screeny of your reputations containing the problematic ones

**Comment by SirJorb** [comment] 2023-04-13 21:26
I think I've determined at least part of what causes the issue, though I'm not sure if it's an issue with the game client or the addon -

It's the categories for reptuations being displayed as reps themselves. 

For example, on my main I have these ones still:

![image](https://user-images.githubusercontent.com/23423782/231886239-b1642f84-3c72-4213-902b-9d9a9c811e94.png)

I currently have all the reps for Cata and TBC marked as inactive, because I've finished them. But if I unmark one...

![image](https://user-images.githubusercontent.com/23423782/231886336-689d84a9-61c8-46c5-8b46-75eb6c8f7d48.png)
![image](https://user-images.githubusercontent.com/23423782/231886355-a3f2ade6-916b-4d8b-89d0-8d272b86963f.png)

**Comment by teelolws** [comment] 2023-04-13 21:35
Yup, its a problem with the game client - that still happens without any addons.

I made it so you can mark the Cataclysm and TBC bars inactive in the last patch though. Have you updated and checked for the inactive option?
![image](https://user-images.githubusercontent.com/49792789/231888137-0b5a2f54-d405-4abb-bd95-846b2588a00c.png)

**Comment by SirJorb** [comment] 2023-04-13 21:39
Oop, I hadn't checked Wowup lately. Yeah, that seems to do it!

**Comment by Hinkyz** [comment] 2023-04-13 22:37
I've hidden everything else. I can't hide any of the ones displayed

![Screenshot 2023-04-13 233540](https://user-images.githubusercontent.com/130223045/231897860-83117361-28f2-4f70-aca1-18c498e613c7.png)
![Screenshot 2023-04-13 233630](https://user-images.githubusercontent.com/130223045/231897864-f7cb53b2-1005-42e7-b63d-6e52fecda80e.png)

**Comment by teelolws** [comment] 2023-04-13 22:39
Have you updated the addon? I fixed those ones a few days ago. Is it turned on? All of those should work.

**Comment by Hinkyz** [comment] 2023-04-13 23:00
Apologies, yeah it wasn't turned on.

The reason I'd turned it off, is because of another issue that I think has been caused by using this addon.
When loading the addon, it just doesn't allow any interaction with the reputation pane, and no expansion titles open.

When loading without the addon, it looks like this (with "Battle for Azeroth" near the bottom):
![image](https://user-images.githubusercontent.com/130223045/231900261-97482d14-b899-470b-baa8-9819b4e63635.png)

When you click on the "Battle for Azeroth" title it now looks like this, (I've made all Battle for Azeorth factions inactive except for "Champions of Azeorth")

![image](https://user-images.githubusercontent.com/130223045/231900442-0c789a5b-3f53-450d-8921-dc2cd1ffdd91.png)


When I untick all the "Battle for Azeroth" factions from being inactive, it looks like this:

![image](https://user-images.githubusercontent.com/130223045/231900770-b3ff5493-f835-4b8d-9b2b-94d3b68443ce.png)
![image](https://user-images.githubusercontent.com/130223045/231900789-e1802e67-15af-47cd-b69e-bb441e3fff5a.png)
Notice that the "Battle for Azeorth" title has disappeared



So it looks like I've managed to hide the "Battle for Azeorth" dropdown somehow, and I believe it was by using this addon. Any idea how to fix this, as it's broken even when I don't have any addons active.

**Comment by teelolws** [comment] 2023-04-13 23:08
Unusual. BFA shouldn't even be at the bottom like that, even without an addon. They're supposed to be in descending order of expansion:
![image](https://user-images.githubusercontent.com/49792789/231901879-b035a602-0942-4547-bfd2-b7af51e4bed2.png)

BFA isn't even a rep the addon is marked to support. It shouldn't be hiding it.

**Comment by teelolws** [comment] 2023-04-13 23:09
That second picture you posted, this one:
![image](https://user-images.githubusercontent.com/49792789/231902066-2fa9e71d-9186-4d5a-b3f3-cec97815f59c.png)

Was this taken without the addon turned on?

**Comment by Hinkyz** [comment] 2023-04-13 23:11
Yeah, all the pictures above are without the addon turned on.

Do you know if there is a file where it is recorded which reputations you have set to be hidden for each character?

**Comment by teelolws** [comment] 2023-04-13 23:14
They're hidden on Blizzards end. For some reason they've made those headers able to be marked hidden, even though you don't get an option. I'll try and find a way to un-hide them again.

They've made those expansion headers hideable - but not the subheaders like Ember Court!

**Comment by Hinkyz** [comment] 2023-04-13 23:19
Oh that's helpful of Blizzard! XD

Thanks for checking into this.

If it helps, I think I was sort of spam clicking to try and hide everthing from older expansions as quickly as possible. At one point I hid something that made everything start to look a little weird, so I stopped.
I now think I was somehow able to hide that "Battle for Azeorth" expansion header

**Comment by teelolws** [comment] 2023-04-13 23:58
Okay, with this update it will cleanup those headers during login.

**Comment by Hinkyz** [comment] 2023-04-14 00:27
So that seems to have fixed the issue with "Battle for Azeroth" expansion header disappearing as it's back now in its proper place:

![image](https://user-images.githubusercontent.com/130223045/231910076-11d2bd85-0d24-4cb5-81e6-2e18b95ef4d8.png)

However, when I was turning factions inactive and active again to make sure it works, I managed to get it stuck unresponsive, and when I reloaded the game, it then looked like this:

![image](https://user-images.githubusercontent.com/130223045/231909973-50ed56b9-2009-46ee-b491-aeef6aba4500.png)


From checking a few more times, it looks like if you have the addon turned on, and turn all "inactive" factions back to "active" (so the "Inactive" header should usually disappear) it then seems to break the addon.
I can make the addon work again by turning it off, making any faction inactive, and turning the addon back on again.


I was able to reproduce this while having all other addons turned off.

**Comment by teelolws** [comment] 2023-04-14 00:59
It wasn't working properly with empty Inactive lists. This fix should make it work when there is one other faction in the Inactive list. However, I cannot add the Inactive header if it is not already there. So if you have nothing marked Inactive, then you mark Horde Expedition inactive, you won't be able to see it anywhere to unmark it until you mark something else inactive. A faction that can normally be marked inactive.

**Comment by Hinkyz** [comment] 2023-04-14 01:17
Looks like the inactive header issue is fixed now.

While trying to check this is working, I had a few issues with making "Valdrakken Accord" inactive and active. Sometimes needed to click the button multiple times, or reload the game to make it work.

It's nothing majort though, and I was able to make it work, but it was a little confusing and not working as expected (one click either way).
Tried this with other factions being hidden at the same time too.

**Comment by teelolws** [comment] 2023-04-14 01:19
Sometimes you will have to scroll your mouse wheel a bit to make it update. The UI has some issues with not accepting my changes immediately.

**Comment by teelolws** [comment] 2023-04-27 05:49
Releasing an overhaul to the internal workings of the addon. Should be no practical difference to everyday use, it just should be much more responsive to changes now, and (hopefully) stop causing conflicts with other addons.

If you have any new issues as a result of todays changes, please create a new ticket.

**Closed as completed** 2023-04-27 05:49 UTC
